### ISSUE TITLE
Cannot connect to gpt

### ISSUE THREAD

**Issue by analyticray** [Norvik-Alexian/Product-Description-Chatbot#1]
I am getting the following error:

**rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"error":"Invalid URL \'None\': No scheme supplied. Perhaps you meant https...**

here's my gpt environment settings:
PRODUCT_DESCRIPTION_ENDPOINT=https://api.openai.com/v1/chat/completions
UC_X_API_KEY=sk-ZjWMuia...mykey

Please advise to resolve the issue

**Comment by Norvik-Alexian** [comment]
I removed API layer and integrated the OpenAI code directly in Rasa chatbot, now you can setup OPENAI_API_KEY in your .env file as environment variable and put your personal OpenAI API key to be able to generate product descriptions.
